name: Code Quality

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  SONAR_PROJECT_KEY: europa-1400-community_europa-1400-tools
  SONAR_PROJECT_NAME: europa-1400-tools
  SONAR_PROJECT_ORGANIZATION: europa-1400-community

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Load cached Poetry venv
        id: cached-poetry-venv
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: poetry-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install

      - name: Run black
        run: |
          poetry run black --check europa-1400-tools tests --diff

      - name: Run isort
        run: |
          poetry run isort --check-only --diff europa-1400-tools tests

      - name: Run mypy
        run: |
          poetry run mypy europa-1400-tools tests

      - name: Run bandit
        run: |
          poetry run bandit -r europa-1400-tools

      - name: Run pytest
        run: |
          poetry run pytest --cov=europa-1400-tools --cov-report=xml

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_PROJECT_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=europa-1400-tools
            -Dsonar.tests=tests/
            -Dsonar.python.version=3.11
